version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: init
          command: |
            tar -xzf swarm.tar.gz -C /tmp/

      - run: 
          name: docker build
          command: docker build -t alioygur/ali .
      - run:
          name: send to hub
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS && docker push alioygur/ali
deployment:
  production:
    branch: master
    commands:
      - ls /tmp