version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: init
          command: |
            tar -xzf swarm.tar.gz -C /tmp/
      - run: 
          name: docker build
          command: docker build -t alioygur/ali .
      - run:
          name: send to hub
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS && docker push alioygur/ali
      - deploy:
          name: deploy
          command: |
            export DOCKER_TLS_VERIFY="1"
            export DOCKER_HOST="tcp://45.55.39.180:2376"
            export DOCKER_CERT_PATH="/tmp/swarm"
            export DOCKER_MACHINE_NAME="swarm"
            docker service create -p 80:8000 --name aliko alioygur/ali